### ISSUE TITLE
I want write NO_PROXY Environment variable

### ISSUE THREAD

**Issue by SHOTANIINA** [MicrosoftDocs/azure-dev-docs.ja-jp#3]
I can't local debug 
but I read the following and solved it
https://github.com/Azure/azure-functions-python-worker/issues/229

Please write Note in this page
if you can't local debug then please check NO_PROXY Environment variable
NO_PROXY=localhost,127.0.0.1
Thanks

Original text
ローカルデバッグが出来なく、資料を探し続けた結果、GitHubリンクから
NO_PROXY環境変数の設定により解決する事ができました。
エラーメッセージのみGoogleで検索してもなかなかたどり着かなく、
解決に時間を要した為、こちらのページに注釈書きをしていただければ幸いです。
gRPC側の影響との事ですが、本ページを参照して始める方も多いと思いますので、
記載する価値があると思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 32211a5a-ad60-b982-b27e-1f2c7caef1c9
* Version Independent ID: 32a098cf-c39d-342b-5b7e-d9a62f6a9454
* Content: [手順 4:VS Code を使用して Azure Functions の Python コードをローカルでデバッグする](https://docs.microsoft.com/ja-jp/azure/python/tutorial-vs-code-serverless-python-04?tabs=bash#feedback)
* Content Source: [python/tutorial-vs-code-serverless-python-04.md](https://github.com/MicrosoftDocs/azure-dev-docs.ja-jp/blob/live/python/tutorial-vs-code-serverless-python-04.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Resolved. Please close.
